// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

package com.alex.game.rank;

public final class RankProto {
  private RankProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqRankListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rank.ReqRankList)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code rank.ReqRankList}
   */
  public  static final class ReqRankList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rank.ReqRankList)
      ReqRankListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReqRankList.newBuilder() to construct.
    private ReqRankList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqRankList() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqRankList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alex.game.rank.RankProto.internal_static_rank_ReqRankList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alex.game.rank.RankProto.internal_static_rank_ReqRankList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alex.game.rank.RankProto.ReqRankList.class, com.alex.game.rank.RankProto.ReqRankList.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alex.game.rank.RankProto.ReqRankList)) {
        return super.equals(obj);
      }
      com.alex.game.rank.RankProto.ReqRankList other = (com.alex.game.rank.RankProto.ReqRankList) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alex.game.rank.RankProto.ReqRankList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alex.game.rank.RankProto.ReqRankList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alex.game.rank.RankProto.ReqRankList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alex.game.rank.RankProto.ReqRankList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alex.game.rank.RankProto.ReqRankList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alex.game.rank.RankProto.ReqRankList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alex.game.rank.RankProto.ReqRankList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alex.game.rank.RankProto.ReqRankList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alex.game.rank.RankProto.ReqRankList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alex.game.rank.RankProto.ReqRankList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alex.game.rank.RankProto.ReqRankList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alex.game.rank.RankProto.ReqRankList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alex.game.rank.RankProto.ReqRankList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rank.ReqRankList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rank.ReqRankList)
        com.alex.game.rank.RankProto.ReqRankListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alex.game.rank.RankProto.internal_static_rank_ReqRankList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alex.game.rank.RankProto.internal_static_rank_ReqRankList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alex.game.rank.RankProto.ReqRankList.class, com.alex.game.rank.RankProto.ReqRankList.Builder.class);
      }

      // Construct using com.alex.game.rank.RankProto.ReqRankList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alex.game.rank.RankProto.internal_static_rank_ReqRankList_descriptor;
      }

      @java.lang.Override
      public com.alex.game.rank.RankProto.ReqRankList getDefaultInstanceForType() {
        return com.alex.game.rank.RankProto.ReqRankList.getDefaultInstance();
      }

      @java.lang.Override
      public com.alex.game.rank.RankProto.ReqRankList build() {
        com.alex.game.rank.RankProto.ReqRankList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.alex.game.rank.RankProto.ReqRankList buildPartial() {
        com.alex.game.rank.RankProto.ReqRankList result = new com.alex.game.rank.RankProto.ReqRankList(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alex.game.rank.RankProto.ReqRankList) {
          return mergeFrom((com.alex.game.rank.RankProto.ReqRankList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alex.game.rank.RankProto.ReqRankList other) {
        if (other == com.alex.game.rank.RankProto.ReqRankList.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alex.game.rank.RankProto.ReqRankList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alex.game.rank.RankProto.ReqRankList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rank.ReqRankList)
    }

    // @@protoc_insertion_point(class_scope:rank.ReqRankList)
    private static final com.alex.game.rank.RankProto.ReqRankList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alex.game.rank.RankProto.ReqRankList();
    }

    public static com.alex.game.rank.RankProto.ReqRankList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqRankList>
        PARSER = new com.google.protobuf.AbstractParser<ReqRankList>() {
      @java.lang.Override
      public ReqRankList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqRankList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqRankList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqRankList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.alex.game.rank.RankProto.ReqRankList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResRankListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rank.ResRankList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
     */
    java.util.List<com.alex.game.rank.RankProto.RankInfo> 
        getRankInfoListList();
    /**
     * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
     */
    com.alex.game.rank.RankProto.RankInfo getRankInfoList(int index);
    /**
     * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
     */
    int getRankInfoListCount();
    /**
     * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
     */
    java.util.List<? extends com.alex.game.rank.RankProto.RankInfoOrBuilder> 
        getRankInfoListOrBuilderList();
    /**
     * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
     */
    com.alex.game.rank.RankProto.RankInfoOrBuilder getRankInfoListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code rank.ResRankList}
   */
  public  static final class ResRankList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rank.ResRankList)
      ResRankListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResRankList.newBuilder() to construct.
    private ResRankList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResRankList() {
      rankInfoList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResRankList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                rankInfoList_ = new java.util.ArrayList<com.alex.game.rank.RankProto.RankInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              rankInfoList_.add(
                  input.readMessage(com.alex.game.rank.RankProto.RankInfo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          rankInfoList_ = java.util.Collections.unmodifiableList(rankInfoList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alex.game.rank.RankProto.internal_static_rank_ResRankList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alex.game.rank.RankProto.internal_static_rank_ResRankList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alex.game.rank.RankProto.ResRankList.class, com.alex.game.rank.RankProto.ResRankList.Builder.class);
    }

    public static final int RANKINFOLIST_FIELD_NUMBER = 1;
    private java.util.List<com.alex.game.rank.RankProto.RankInfo> rankInfoList_;
    /**
     * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
     */
    public java.util.List<com.alex.game.rank.RankProto.RankInfo> getRankInfoListList() {
      return rankInfoList_;
    }
    /**
     * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
     */
    public java.util.List<? extends com.alex.game.rank.RankProto.RankInfoOrBuilder> 
        getRankInfoListOrBuilderList() {
      return rankInfoList_;
    }
    /**
     * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
     */
    public int getRankInfoListCount() {
      return rankInfoList_.size();
    }
    /**
     * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
     */
    public com.alex.game.rank.RankProto.RankInfo getRankInfoList(int index) {
      return rankInfoList_.get(index);
    }
    /**
     * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
     */
    public com.alex.game.rank.RankProto.RankInfoOrBuilder getRankInfoListOrBuilder(
        int index) {
      return rankInfoList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < rankInfoList_.size(); i++) {
        output.writeMessage(1, rankInfoList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < rankInfoList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, rankInfoList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alex.game.rank.RankProto.ResRankList)) {
        return super.equals(obj);
      }
      com.alex.game.rank.RankProto.ResRankList other = (com.alex.game.rank.RankProto.ResRankList) obj;

      boolean result = true;
      result = result && getRankInfoListList()
          .equals(other.getRankInfoListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRankInfoListCount() > 0) {
        hash = (37 * hash) + RANKINFOLIST_FIELD_NUMBER;
        hash = (53 * hash) + getRankInfoListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alex.game.rank.RankProto.ResRankList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alex.game.rank.RankProto.ResRankList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alex.game.rank.RankProto.ResRankList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alex.game.rank.RankProto.ResRankList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alex.game.rank.RankProto.ResRankList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alex.game.rank.RankProto.ResRankList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alex.game.rank.RankProto.ResRankList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alex.game.rank.RankProto.ResRankList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alex.game.rank.RankProto.ResRankList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alex.game.rank.RankProto.ResRankList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alex.game.rank.RankProto.ResRankList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alex.game.rank.RankProto.ResRankList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alex.game.rank.RankProto.ResRankList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rank.ResRankList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rank.ResRankList)
        com.alex.game.rank.RankProto.ResRankListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alex.game.rank.RankProto.internal_static_rank_ResRankList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alex.game.rank.RankProto.internal_static_rank_ResRankList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alex.game.rank.RankProto.ResRankList.class, com.alex.game.rank.RankProto.ResRankList.Builder.class);
      }

      // Construct using com.alex.game.rank.RankProto.ResRankList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRankInfoListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (rankInfoListBuilder_ == null) {
          rankInfoList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          rankInfoListBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alex.game.rank.RankProto.internal_static_rank_ResRankList_descriptor;
      }

      @java.lang.Override
      public com.alex.game.rank.RankProto.ResRankList getDefaultInstanceForType() {
        return com.alex.game.rank.RankProto.ResRankList.getDefaultInstance();
      }

      @java.lang.Override
      public com.alex.game.rank.RankProto.ResRankList build() {
        com.alex.game.rank.RankProto.ResRankList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.alex.game.rank.RankProto.ResRankList buildPartial() {
        com.alex.game.rank.RankProto.ResRankList result = new com.alex.game.rank.RankProto.ResRankList(this);
        int from_bitField0_ = bitField0_;
        if (rankInfoListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            rankInfoList_ = java.util.Collections.unmodifiableList(rankInfoList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.rankInfoList_ = rankInfoList_;
        } else {
          result.rankInfoList_ = rankInfoListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alex.game.rank.RankProto.ResRankList) {
          return mergeFrom((com.alex.game.rank.RankProto.ResRankList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alex.game.rank.RankProto.ResRankList other) {
        if (other == com.alex.game.rank.RankProto.ResRankList.getDefaultInstance()) return this;
        if (rankInfoListBuilder_ == null) {
          if (!other.rankInfoList_.isEmpty()) {
            if (rankInfoList_.isEmpty()) {
              rankInfoList_ = other.rankInfoList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRankInfoListIsMutable();
              rankInfoList_.addAll(other.rankInfoList_);
            }
            onChanged();
          }
        } else {
          if (!other.rankInfoList_.isEmpty()) {
            if (rankInfoListBuilder_.isEmpty()) {
              rankInfoListBuilder_.dispose();
              rankInfoListBuilder_ = null;
              rankInfoList_ = other.rankInfoList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              rankInfoListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRankInfoListFieldBuilder() : null;
            } else {
              rankInfoListBuilder_.addAllMessages(other.rankInfoList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alex.game.rank.RankProto.ResRankList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alex.game.rank.RankProto.ResRankList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.alex.game.rank.RankProto.RankInfo> rankInfoList_ =
        java.util.Collections.emptyList();
      private void ensureRankInfoListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          rankInfoList_ = new java.util.ArrayList<com.alex.game.rank.RankProto.RankInfo>(rankInfoList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.alex.game.rank.RankProto.RankInfo, com.alex.game.rank.RankProto.RankInfo.Builder, com.alex.game.rank.RankProto.RankInfoOrBuilder> rankInfoListBuilder_;

      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public java.util.List<com.alex.game.rank.RankProto.RankInfo> getRankInfoListList() {
        if (rankInfoListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rankInfoList_);
        } else {
          return rankInfoListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public int getRankInfoListCount() {
        if (rankInfoListBuilder_ == null) {
          return rankInfoList_.size();
        } else {
          return rankInfoListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public com.alex.game.rank.RankProto.RankInfo getRankInfoList(int index) {
        if (rankInfoListBuilder_ == null) {
          return rankInfoList_.get(index);
        } else {
          return rankInfoListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public Builder setRankInfoList(
          int index, com.alex.game.rank.RankProto.RankInfo value) {
        if (rankInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankInfoListIsMutable();
          rankInfoList_.set(index, value);
          onChanged();
        } else {
          rankInfoListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public Builder setRankInfoList(
          int index, com.alex.game.rank.RankProto.RankInfo.Builder builderForValue) {
        if (rankInfoListBuilder_ == null) {
          ensureRankInfoListIsMutable();
          rankInfoList_.set(index, builderForValue.build());
          onChanged();
        } else {
          rankInfoListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public Builder addRankInfoList(com.alex.game.rank.RankProto.RankInfo value) {
        if (rankInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankInfoListIsMutable();
          rankInfoList_.add(value);
          onChanged();
        } else {
          rankInfoListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public Builder addRankInfoList(
          int index, com.alex.game.rank.RankProto.RankInfo value) {
        if (rankInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankInfoListIsMutable();
          rankInfoList_.add(index, value);
          onChanged();
        } else {
          rankInfoListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public Builder addRankInfoList(
          com.alex.game.rank.RankProto.RankInfo.Builder builderForValue) {
        if (rankInfoListBuilder_ == null) {
          ensureRankInfoListIsMutable();
          rankInfoList_.add(builderForValue.build());
          onChanged();
        } else {
          rankInfoListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public Builder addRankInfoList(
          int index, com.alex.game.rank.RankProto.RankInfo.Builder builderForValue) {
        if (rankInfoListBuilder_ == null) {
          ensureRankInfoListIsMutable();
          rankInfoList_.add(index, builderForValue.build());
          onChanged();
        } else {
          rankInfoListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public Builder addAllRankInfoList(
          java.lang.Iterable<? extends com.alex.game.rank.RankProto.RankInfo> values) {
        if (rankInfoListBuilder_ == null) {
          ensureRankInfoListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rankInfoList_);
          onChanged();
        } else {
          rankInfoListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public Builder clearRankInfoList() {
        if (rankInfoListBuilder_ == null) {
          rankInfoList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          rankInfoListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public Builder removeRankInfoList(int index) {
        if (rankInfoListBuilder_ == null) {
          ensureRankInfoListIsMutable();
          rankInfoList_.remove(index);
          onChanged();
        } else {
          rankInfoListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public com.alex.game.rank.RankProto.RankInfo.Builder getRankInfoListBuilder(
          int index) {
        return getRankInfoListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public com.alex.game.rank.RankProto.RankInfoOrBuilder getRankInfoListOrBuilder(
          int index) {
        if (rankInfoListBuilder_ == null) {
          return rankInfoList_.get(index);  } else {
          return rankInfoListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public java.util.List<? extends com.alex.game.rank.RankProto.RankInfoOrBuilder> 
           getRankInfoListOrBuilderList() {
        if (rankInfoListBuilder_ != null) {
          return rankInfoListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rankInfoList_);
        }
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public com.alex.game.rank.RankProto.RankInfo.Builder addRankInfoListBuilder() {
        return getRankInfoListFieldBuilder().addBuilder(
            com.alex.game.rank.RankProto.RankInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public com.alex.game.rank.RankProto.RankInfo.Builder addRankInfoListBuilder(
          int index) {
        return getRankInfoListFieldBuilder().addBuilder(
            index, com.alex.game.rank.RankProto.RankInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .rank.RankInfo rankInfoList = 1;</code>
       */
      public java.util.List<com.alex.game.rank.RankProto.RankInfo.Builder> 
           getRankInfoListBuilderList() {
        return getRankInfoListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.alex.game.rank.RankProto.RankInfo, com.alex.game.rank.RankProto.RankInfo.Builder, com.alex.game.rank.RankProto.RankInfoOrBuilder> 
          getRankInfoListFieldBuilder() {
        if (rankInfoListBuilder_ == null) {
          rankInfoListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.alex.game.rank.RankProto.RankInfo, com.alex.game.rank.RankProto.RankInfo.Builder, com.alex.game.rank.RankProto.RankInfoOrBuilder>(
                  rankInfoList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          rankInfoList_ = null;
        }
        return rankInfoListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rank.ResRankList)
    }

    // @@protoc_insertion_point(class_scope:rank.ResRankList)
    private static final com.alex.game.rank.RankProto.ResRankList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alex.game.rank.RankProto.ResRankList();
    }

    public static com.alex.game.rank.RankProto.ResRankList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResRankList>
        PARSER = new com.google.protobuf.AbstractParser<ResRankList>() {
      @java.lang.Override
      public ResRankList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResRankList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResRankList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResRankList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.alex.game.rank.RankProto.ResRankList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RankInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rank.RankInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 playerId = 1;</code>
     */
    long getPlayerId();

    /**
     * <code>int32 iconId = 2;</code>
     */
    int getIconId();

    /**
     * <code>string nickName = 3;</code>
     */
    java.lang.String getNickName();
    /**
     * <code>string nickName = 3;</code>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    /**
     * <code>int64 gold = 4;</code>
     */
    long getGold();

    /**
     * <code>int32 rank = 5;</code>
     */
    int getRank();

    /**
     * <code>string signature = 6;</code>
     */
    java.lang.String getSignature();
    /**
     * <code>string signature = 6;</code>
     */
    com.google.protobuf.ByteString
        getSignatureBytes();
  }
  /**
   * <pre>
   *排行信息
   * </pre>
   *
   * Protobuf type {@code rank.RankInfo}
   */
  public  static final class RankInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rank.RankInfo)
      RankInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RankInfo.newBuilder() to construct.
    private RankInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RankInfo() {
      playerId_ = 0L;
      iconId_ = 0;
      nickName_ = "";
      gold_ = 0L;
      rank_ = 0;
      signature_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RankInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              playerId_ = input.readInt64();
              break;
            }
            case 16: {

              iconId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              nickName_ = s;
              break;
            }
            case 32: {

              gold_ = input.readInt64();
              break;
            }
            case 40: {

              rank_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              signature_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alex.game.rank.RankProto.internal_static_rank_RankInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alex.game.rank.RankProto.internal_static_rank_RankInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alex.game.rank.RankProto.RankInfo.class, com.alex.game.rank.RankProto.RankInfo.Builder.class);
    }

    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerId_;
    /**
     * <code>int64 playerId = 1;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    public static final int ICONID_FIELD_NUMBER = 2;
    private int iconId_;
    /**
     * <code>int32 iconId = 2;</code>
     */
    public int getIconId() {
      return iconId_;
    }

    public static final int NICKNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object nickName_;
    /**
     * <code>string nickName = 3;</code>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickName_ = s;
        return s;
      }
    }
    /**
     * <code>string nickName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GOLD_FIELD_NUMBER = 4;
    private long gold_;
    /**
     * <code>int64 gold = 4;</code>
     */
    public long getGold() {
      return gold_;
    }

    public static final int RANK_FIELD_NUMBER = 5;
    private int rank_;
    /**
     * <code>int32 rank = 5;</code>
     */
    public int getRank() {
      return rank_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 6;
    private volatile java.lang.Object signature_;
    /**
     * <code>string signature = 6;</code>
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signature_ = s;
        return s;
      }
    }
    /**
     * <code>string signature = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerId_ != 0L) {
        output.writeInt64(1, playerId_);
      }
      if (iconId_ != 0) {
        output.writeInt32(2, iconId_);
      }
      if (!getNickNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nickName_);
      }
      if (gold_ != 0L) {
        output.writeInt64(4, gold_);
      }
      if (rank_ != 0) {
        output.writeInt32(5, rank_);
      }
      if (!getSignatureBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, signature_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      if (iconId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, iconId_);
      }
      if (!getNickNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nickName_);
      }
      if (gold_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, gold_);
      }
      if (rank_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, rank_);
      }
      if (!getSignatureBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, signature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alex.game.rank.RankProto.RankInfo)) {
        return super.equals(obj);
      }
      com.alex.game.rank.RankProto.RankInfo other = (com.alex.game.rank.RankProto.RankInfo) obj;

      boolean result = true;
      result = result && (getPlayerId()
          == other.getPlayerId());
      result = result && (getIconId()
          == other.getIconId());
      result = result && getNickName()
          .equals(other.getNickName());
      result = result && (getGold()
          == other.getGold());
      result = result && (getRank()
          == other.getRank());
      result = result && getSignature()
          .equals(other.getSignature());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlayerId());
      hash = (37 * hash) + ICONID_FIELD_NUMBER;
      hash = (53 * hash) + getIconId();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickName().hashCode();
      hash = (37 * hash) + GOLD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGold());
      hash = (37 * hash) + RANK_FIELD_NUMBER;
      hash = (53 * hash) + getRank();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alex.game.rank.RankProto.RankInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alex.game.rank.RankProto.RankInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alex.game.rank.RankProto.RankInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alex.game.rank.RankProto.RankInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alex.game.rank.RankProto.RankInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alex.game.rank.RankProto.RankInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alex.game.rank.RankProto.RankInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alex.game.rank.RankProto.RankInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alex.game.rank.RankProto.RankInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alex.game.rank.RankProto.RankInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alex.game.rank.RankProto.RankInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alex.game.rank.RankProto.RankInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alex.game.rank.RankProto.RankInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *排行信息
     * </pre>
     *
     * Protobuf type {@code rank.RankInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rank.RankInfo)
        com.alex.game.rank.RankProto.RankInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alex.game.rank.RankProto.internal_static_rank_RankInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alex.game.rank.RankProto.internal_static_rank_RankInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alex.game.rank.RankProto.RankInfo.class, com.alex.game.rank.RankProto.RankInfo.Builder.class);
      }

      // Construct using com.alex.game.rank.RankProto.RankInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        playerId_ = 0L;

        iconId_ = 0;

        nickName_ = "";

        gold_ = 0L;

        rank_ = 0;

        signature_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alex.game.rank.RankProto.internal_static_rank_RankInfo_descriptor;
      }

      @java.lang.Override
      public com.alex.game.rank.RankProto.RankInfo getDefaultInstanceForType() {
        return com.alex.game.rank.RankProto.RankInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.alex.game.rank.RankProto.RankInfo build() {
        com.alex.game.rank.RankProto.RankInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.alex.game.rank.RankProto.RankInfo buildPartial() {
        com.alex.game.rank.RankProto.RankInfo result = new com.alex.game.rank.RankProto.RankInfo(this);
        result.playerId_ = playerId_;
        result.iconId_ = iconId_;
        result.nickName_ = nickName_;
        result.gold_ = gold_;
        result.rank_ = rank_;
        result.signature_ = signature_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alex.game.rank.RankProto.RankInfo) {
          return mergeFrom((com.alex.game.rank.RankProto.RankInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alex.game.rank.RankProto.RankInfo other) {
        if (other == com.alex.game.rank.RankProto.RankInfo.getDefaultInstance()) return this;
        if (other.getPlayerId() != 0L) {
          setPlayerId(other.getPlayerId());
        }
        if (other.getIconId() != 0) {
          setIconId(other.getIconId());
        }
        if (!other.getNickName().isEmpty()) {
          nickName_ = other.nickName_;
          onChanged();
        }
        if (other.getGold() != 0L) {
          setGold(other.getGold());
        }
        if (other.getRank() != 0) {
          setRank(other.getRank());
        }
        if (!other.getSignature().isEmpty()) {
          signature_ = other.signature_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alex.game.rank.RankProto.RankInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alex.game.rank.RankProto.RankInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long playerId_ ;
      /**
       * <code>int64 playerId = 1;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>int64 playerId = 1;</code>
       */
      public Builder setPlayerId(long value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private int iconId_ ;
      /**
       * <code>int32 iconId = 2;</code>
       */
      public int getIconId() {
        return iconId_;
      }
      /**
       * <code>int32 iconId = 2;</code>
       */
      public Builder setIconId(int value) {
        
        iconId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 iconId = 2;</code>
       */
      public Builder clearIconId() {
        
        iconId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nickName_ = "";
      /**
       * <code>string nickName = 3;</code>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nickName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nickName = 3;</code>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nickName = 3;</code>
       */
      public Builder clearNickName() {
        
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <code>string nickName = 3;</code>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickName_ = value;
        onChanged();
        return this;
      }

      private long gold_ ;
      /**
       * <code>int64 gold = 4;</code>
       */
      public long getGold() {
        return gold_;
      }
      /**
       * <code>int64 gold = 4;</code>
       */
      public Builder setGold(long value) {
        
        gold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 gold = 4;</code>
       */
      public Builder clearGold() {
        
        gold_ = 0L;
        onChanged();
        return this;
      }

      private int rank_ ;
      /**
       * <code>int32 rank = 5;</code>
       */
      public int getRank() {
        return rank_;
      }
      /**
       * <code>int32 rank = 5;</code>
       */
      public Builder setRank(int value) {
        
        rank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 rank = 5;</code>
       */
      public Builder clearRank() {
        
        rank_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object signature_ = "";
      /**
       * <code>string signature = 6;</code>
       */
      public java.lang.String getSignature() {
        java.lang.Object ref = signature_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          signature_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string signature = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        java.lang.Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string signature = 6;</code>
       */
      public Builder setSignature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string signature = 6;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <code>string signature = 6;</code>
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        signature_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rank.RankInfo)
    }

    // @@protoc_insertion_point(class_scope:rank.RankInfo)
    private static final com.alex.game.rank.RankProto.RankInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alex.game.rank.RankProto.RankInfo();
    }

    public static com.alex.game.rank.RankProto.RankInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RankInfo>
        PARSER = new com.google.protobuf.AbstractParser<RankInfo>() {
      @java.lang.Override
      public RankInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RankInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RankInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RankInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.alex.game.rank.RankProto.RankInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rank_ReqRankList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rank_ReqRankList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rank_ResRankList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rank_ResRankList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rank_RankInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rank_RankInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nrank.proto\022\004rank\"\r\n\013ReqRankList\"3\n\013Res" +
      "RankList\022$\n\014rankInfoList\030\001 \003(\0132\016.rank.Ra" +
      "nkInfo\"m\n\010RankInfo\022\020\n\010playerId\030\001 \001(\003\022\016\n\006" +
      "iconId\030\002 \001(\005\022\020\n\010nickName\030\003 \001(\t\022\014\n\004gold\030\004" +
      " \001(\003\022\014\n\004rank\030\005 \001(\005\022\021\n\tsignature\030\006 \001(\tB\037\n" +
      "\022com.alex.game.rankB\tRankProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_rank_ReqRankList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rank_ReqRankList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rank_ReqRankList_descriptor,
        new java.lang.String[] { });
    internal_static_rank_ResRankList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rank_ResRankList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rank_ResRankList_descriptor,
        new java.lang.String[] { "RankInfoList", });
    internal_static_rank_RankInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rank_RankInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rank_RankInfo_descriptor,
        new java.lang.String[] { "PlayerId", "IconId", "NickName", "Gold", "Rank", "Signature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
